// <auto-generated />
namespace Developer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class C11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C11));
        
        string IMigrationMetadata.Id
        {
            get { return "201803022358215_C11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
